# Generated by Django 3.0.8 on 2020-11-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201109_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'date'},
        ),
    ]
