# Generated by Django 3.0.8 on 2020-11-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201111_0509'),
        ('blog', '0017_remove_post_snippet'),
    ]

    operations = [
    ]
