# Generated by Django 3.0.8 on 2020-11-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_merge_20201111_1702'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_title_e1c6f7_idx',
        ),
    ]
